### PR TITLE
Adding support for QML files

### PR DESCRIPTION
**Pull request by BoboTiG**

### CODE REVIEW

**Review by eliben — APPROVED** [review]

**Comment by eliben** [comment]
@BoboTiG do you have any additional changes incoming? I was thinking of doing a new release for pss (it's been quite a while since the previous one).

**Comment by BoboTiG** [comment]
No, it is all good on my side :)

**Comment by eliben** [comment]
SG, thanks for your contributions!

**Comment by BoboTiG** [comment]
And thanks for your reactivity :)

**Pull request merged**
